// 🧙‍♀️ KABBALISTIC TREE OF LIFE
// Professional-grade Kabbalah integration with full correspondences

export interface Sephirah {
  id: number;
  name: string;
  hebrew: string;
  meaning: string;
  archangel: string;
  angelicChoir: string;
  planet: string;
  element: string | null;
  astrological: string[];
  weapon: string;
  virtue: string[];
  vice: string[];
  gemstone: string[];
  color: string[];
  incense: string[];
  deity: string;
  psychological: string;
  spiritual: string;
  path: number;
  connections: number[];
}

export const TREE_OF_LIFE: Sephirah[] = [
  {
    id: 1,
    name: "Kether",
    hebrew: "כתר",
    meaning: "Crown",
    archangel: "Metatron",
    angelicChoir: "Chayoth Ha Kadesh",
    planet: "Pluto",
    element: null,
    astrological: ["Scorpio", "Capricorn"],
    weapon: "Crown of Jewels",
    virtue: ["Pure Will", "Divine Emanation"],
    vice: ["Withdrawn"],
    gemstone: ["Diamond", "Amethyst"],
    color: ["Brilliant White", "Gold"],
    incense: ["Frankincense"],
    deity: "Ain Soph Aur",
    psychological: "Superconscious mind, pure being",
    spiritual: "Unity with Godhead, enlightenment",
    path: 11,
    connections: [2]
  },
  {
    id: 2,
    name: "Chokmah",
    hebrew: "חכמה",
    meaning: "Wisdom",
    archangel: "Raziel",
    angelicChoir: "Auphanim",
    planet: "Neptune",
    element: null,
    astrological: ["Pisces"],
    weapon: "Wand of Force",
    virtue: ["Enlightening", "Influence"],
    vice: ["Foolish"],
    gemstone: ["Lapis Lazuli", "Aquamarine"],
    color: ["Gray", "Amber"],
    incense: ["Camphor"],
    deity: "Yah",
    psychological: "Intuition, insight, wisdom",
    spiritual: "God's wisdom, masculine principle",
    path: 13,
    connections: [1, 3]
  },
  {
    id: 3,
    name: "Binah",
    hebrew: "בינה",
    meaning: "Understanding",
    archangel: "Tzaphkiel",
    angelicChoir: "Aralim",
    planet: "Saturn",
    element: null,
    astrological: ["Capricorn"],
    weapon: "Sword of Justice",
    virtue: ["Silence", "Wisdom"],
    vice: ["Does not transform", "Capricious"],
    gemstone: ["Onyx", "Lapis Lazuli"],
    color: ["Mauve", "Black"],
    incense: ["Myrrh"],
    deity: "Yahweh Elohim",
    psychological: "Analysis, form, structure, comprehension",
    spiritual: "Divine understanding, feminine principle",
    path: 17,
    connections: [2, 6, 27]
  },
  {
    id: 4,
    name: "Chesed",
    hebrew: "חסד",
    meaning: "Mercy",
    archangel: "Tzadkiel",
    angelicChoir: "Chasmalim",
    planet: "Jupiter",
    element: "Water",
    astrological: ["Pisces", "Sagittarius"],
    weapon: "Orbs of Power",
    virtue: ["Grace", "Compassion", "Obedience", "Trumpet", "Lute"],
    vice: ["False paternalism", "Tyranny"],
    gemstone: ["Amethyst", "Sapphire"],
    color: ["Deep Blue", "Purple"],
    incense: ["Cedar"],
    deity: "El",
    psychological: "Generosity, giving, compassion",
    spiritual: "God's mercy, benevolent king",
    path: 19,
    connections: [5]
  },
  {
    id: 5,
    name: "Geburah",
    hebrew: "גבורה",
    meaning: "Severity",
    archangel: "Samael",
    angelicChoir: "Seraphim",
    planet: "Mars",
    element: "Fire",
    astrological: ["Aries"],
    weapon: "Five-pointed Star",
    virtue: ["Energy", "Courage", "Justice"],
    vice: ["Cruelty", "Destruction"],
    gemstone: ["Ruby", "Bloodstone"],
    color: ["Deep Red", "Scarlet"],
    incense: ["Dragon's Blood"],
    deity: "Elohim Gibor",
    psychological: "Strength, discipline, power, authority",
    spiritual: "God's justice, severity",
    path: 15,
    connections: [4, 6]
  },
  {
    id: 6,
    name: "Tiphareth",
    hebrew: "תפארת",
    meaning: "Beauty",
    archangel: "Raphael",
    angelicChoir: "Malakim",
    planet: "Sol",
    element: "Air",
    astrological: ["Leo"],
    weapon: "Lamp of Beauty",
    virtue: ["Devotion to Higher", "Spirit of Fire"],
    vice: ["False Imagination"],
    gemstone: ["Diamond", "Emerald"],
    color: ["Yellow", "Golden Yellow"],
    incense: ["Olibanum"],
    deity: "YHWH Eloah Vedaath",
    psychological: "Balance, harmony, integration",
    spiritual: "Christ consciousness, self-sacrifice",
    path: 6,
    connections: [3, 5, 9, 27]
  },
  {
    id: 7,
    name: "Netzach",
    hebrew: "נצח",
    meaning: "Victory",
    archangel: "Haniel",
    angelicChoir: "Elohim",
    planet: "Venus",
    element: "Water",
    astrological: ["Libra", "Taurus"],
    weapon: "Rose",
    virtue: ["Victory", "Unselfishness"],
    vice: ["Lust", "Inconstancy"],
    gemstone: ["Emerald", "Rose Quartz"],
    color: ["Emerald Green", "Deep Rose"],
    incense: ["Rose"],
    deity: "YHWH Tzabaoth",
    psychological: "Love, emotion, relationships",
    spiritual: "Eternal victory, divine love",
    path: 23,
    connections: [8]
  },
  {
    id: 8,
    name: "Hod",
    hebrew: "הוד",
    meaning: "Splendor",
    archangel: "Michael",
    angelicChoir: "Bene Elohim",
    planet: "Mercury",
    element: "Earth",
    astrological: ["Virgo", "Gemini"],
    weapon: "Names and Images",
    virtue: ["Honesty", "Truthfulness", "Stability"],
    vice: ["Dishonesty", "Over-intellectualization"],
    gemstone: ["Topaz", "Mica"],
    color: ["Orange", "Crimson"],
    incense: ["Agatha Wood"],
    deity: "Elohim Tzabaoth",
    psychological: "Intellect, communication, science, reason",
    spiritual: "Divine mercy, splendor of God",
    path: 19,
    connections: [7, 9]
  },
  {
    id: 9,
    name: "Yesod",
    hebrew: "יסוד",
    meaning: "Foundation",
    archangel: "Gabriel",
    angelicChoir: "Kerubim",
    planet: "Luna",
    element: "Aether",
    astrological: ["Pisces", "Cancer"],
    weapon: "Perfumes and Magical Instruments",
    virtue: ["Independence", "Creativity"],
    vice: ["Falsehood", "Trickiness"],
    gemstone: ["Quartz", "Pearl"],
    color: ["Violet", "Silver"],
    incense: ["Jasmine"],
    deity: "Shaddai El Chai",
    psychological: "Foundation of personality, unconscious",
    spiritual: "Foundation of all creation",
    path: 32,
    connections: [6, 8, 10]
  },
  {
    id: 10,
    name: "Malkuth",
    hebrew: "מלכות",
    meaning: "Kingdom",
    archangel: "Sandalphon",
    angelicChoir: "Ashim",
    planet: "Earth",
    element: "Earth",
    astrological: ["Taurus", "Virgo", "Capricorn"],
    weapon: "Fortress of Day and Night",
    virtue: ["Discernment", "Discretion"],
    vice: ["Avarice", "Inertia"],
    gemstone: ["Salt", "Ivory"],
    color: ["Citrine", "Russ Green", "Olive"],
    incense: ["Dittany of Crete"],
    deity: "Adonai ha-Aretz",
    psychological: "Physical body, material reality, manifestation",
    spiritual: "Bringing spirit into matter",
    path: 32,
    connections: [9]
  }
];

// Paths between Sephiroth (21 total)
export interface Path {
  id: number;
  from: number;
  to: number;
  hebrew: string;
  meaning: string;
  tarot: string;
  astrology: string[];
  color: string;
  stone: string;
  plant: string;
  image: string;
  virtue: string;
  advice: string;
  warning: string;
}

export const TREE_OF_LIFE_PATHS: Path[] = [
  {
    id: 11,
    from: 1,
    to: 2,
    hebrew: "אלף",
    meaning: "Ox",
    tarot: "The Fool",
    astrology: ["Uranus"],
    color: "White",
    stone: "Peridot",
    plant: "Poppy",
    image: "Wise fool",
    virtue: "Intuition",
    advice: "Trust your inner guidance",
    warning: "Beware of naivety"
  },
  {
    id: 12,
    from: 1,
    to: 3,
    hebrew: "בית",
    meaning: "House",
    tarot: "The Magician",
    astrology: ["Mercury"],
    color: "Yellow",
    stone: "Turquoise",
    plant: "Hazel",
    image: "Magical teacher",
    virtue: "Will power",
    advice: "Manifest your intentions",
    warning: "Don't manipulate others"
  },
  {
    id: 13,
    from: 2,
    to: 3,
    hebrew: "גימל",
    meaning: "Camel",
    tarot: "The High Priestess",
    astrology: ["Moon"],
    color: "Blue",
    stone: "Pearl",
    plant: "Almond",
    image: "Mystical priestess",
    virtue: "Intuition",
    advice: "Trust the unseen",
    warning: "Beware of illusion"
  },
  {
    id: 14,
    from: 2,
    to: 6,
    hebrew: "דלת",
    meaning: "Door",
    tarot: "The Empress",
    astrology: ["Venus"],
    color: "Green",
    stone: "Emerald",
    plant: "Rose",
    image: "Fertile mother",
    virtue: "Creativity",
    advice: "Nurture growth",
    warning: "Avoid stagnation"
  },
  {
    id: 15,
    from: 4,
    to: 5,
    hebrew: "הא",
    meaning: "Window",
    tarot: "The Emperor",
    astrology: ["Aries"],
    color: "Red",
    stone: "Ruby",
    plant: "Oak",
    image: "Imperial leader",
    virtue: "Strength",
    advice: "Take responsibility",
    warning: "Avoid tyranny"
  },
  {
    id: 16,
    from: 4,
    to: 6,
    hebrew: "ויו",
    meaning: "Nail",
    tarot: "The Hierophant",
    astrology: ["Taurus"],
    color: "Orange-Red",
    stone: "Topaz",
    plant: "Vine",
    image: "Spiritual teacher",
    virtue: "Teaching wisdom",
    advice: "Share knowledge",
    warning: "Don't impose beliefs"
  },
  {
    id: 17,
    from: 3,
    to: 6,
    hebrew: "זין",
    meaning: "Sword",
    tarot: "The Lovers",
    astrology: ["Gemini"],
    color: "Pale Yellow",
    stone: "Alexandrite",
    plant: "Orchid",
    image: "Loving union",
    virtue: "Harmony",
    advice: "Make wise choices",
    warning: "Consider consequences"
  },
  {
    id: 18,
    from: 5,
    to: 6,
    hebrew: "חית",
    meaning: "Fence",
    tarot: "The Chariot",
    astrology: ["Cancer"],
    color: "Amber",
    stone: "Topaz",
    plant: "Ivy",
    image: "Victorious warrior",
    virtue: "Determination",
    advice: "Control your direction",
    warning: "Don't lose focus"
  },
  {
    id: 19,
    from: 4,
    to: 7,
    hebrew: "טית",
    meaning: "Snake",
    tarot: "Strength",
    astrology: ["Leo"],
    color: "Strong Yellow",
    stone: "Jacinth",
    plant: "Sunflower",
    image: "Inner courage",
    virtue: "Patience",
    advice: "Be gentle and firm",
    warning: "Rage is destructive"
  },
  {
    id: 20,
    from: 5,
    to: 8,
    hebrew: "יוד",
    meaning: "Hand",
    tarot: "The Hermit",
    astrology: ["Virgo"],
    color: "Greenish Yellow",
    stone: "Peridot",
    plant: "Pear tree",
    image: "Wise guide",
    virtue: "Prudence",
    advice: "Seek self-knowledge",
    warning: "Isolation is unwise"
  },
  {
    id: 21,
    from: 6,
    to: 7,
    hebrew: "כף",
    meaning: "Palm",
    tarot: "Wheel of Fortune",
    astrology: ["Jupiter"],
    color: "Violet",
    stone: "Amethyst",
    plant: "Honeysuckle",
    image: "Turning destiny",
    virtue: "Acceptance",
    advice: "Go with the flow",
    warning: "Don't force outcomes"
  },
  {
    id: 22,
    from: 6,
    to: 8,
    hebrew: "למד",
    meaning: "Ox-goad",
    tarot: "Justice",
    astrology: ["Libra"],
    color: "Emerald Green",
    stone: "Emerald",
    plant: "Poppy",
    image: "Balanced scales",
    virtue: "Justice",
    advice: "Balance all things",
    warning: "Injustice breeds karma"
  },
  {
    id: 23,
    from: 6,
    to: 9,
    hebrew: "מם",
    meaning: "Water",
    tarot: "The Hanged Man",
    astrology: ["Water"],
    color: "Deep Blue",
    stone: "Aquamarine",
    plant: "Yew",
    image: "Suspension",
    virtue: "Sacrifice",
    advice: "Embrace new perspectives",
    warning: "Don't hang indefinitely"
  },
  {
    id: 24,
    from: 7,
    to: 9,
    hebrew: "נון",
    meaning: "Fish",
    tarot: "Death",
    astrology: ["Scorpio"],
    color: "Green-Blue",
    stone: "Green Calcite",
    plant: "Cypress",
    image: "Transformation",
    virtue: "Regeneration",
    advice: "Embrace change",
    warning: "Fear death's wisdom"
  },
  {
    id: 25,
    from: 7,
    to: 10,
    hebrew: "סמך",
    meaning: "Prop",
    tarot: "Temperance",
    astrology: ["Sagittarius"],
    color: "Blue",
    stone: "Blue Sapphire",
    plant: "Sage",
    image: "Divine mediator",
    virtue: "Moderation",
    advice: "Find middle way",
    warning: "Extremes destroy balance"
  },
  {
    id: 26,
    from: 8,
    to: 9,
    hebrew: "עין",
    meaning: "Eye",
    tarot: "The Devil",
    astrology: ["Capricorn"],
    color: "Indigo",
    stone: "Black Diamond",
    plant: "Hemp",
    image: "Shadow integration",
    virtue: "Wisdom",
    advice: "Face shadow self",
    warning: "Addiction is bondage"
  },
  {
    id: 27,
    from: 8,
    to: 10,
    hebrew: "פא",
    meaning: "Mouth",
    tarot: "The Tower",
    astrology: ["Mars"],
    color: "Red-Orange",
    stone: "Rutile",
    plant: "Raspberry",
    image: "Divine destruction",
    virtue: "Sudden awakening",
    advice: "Break limitation",
    warning: "Forced change hurts"
  },
  {
    id: 28,
    from: 9,
    to: 10,
    hebrew: "צדי",
    meaning: "Fish-hook",
    tarot: "The Star",
    astrology: ["Aquarius"],
    color: "Violet",
    stone: "Clear Quartz",
    plant: "Nightshade",
    image: "Hope reborn",
    virtue: "Inspiration",
    advice: "Have faith in miracles",
    warning: "False hope deceives"
  },
  {
    id: 29,
    from: 3,
    to: 5,
    hebrew: "ק biophysicalך",
    meaning: "Back of head",
    tarot: "The Moon",
    astrology: ["Pisces"],
    color: "Silver",
    stone: "Mother-of-Pearl",
    plant: "Moonwort",
    image: "Deceptive illusion",
    virtue: "Dream wisdom",
    advice: "Trust inner guidance",
    warning: "Deceptive appearances"
  },
  {
    id: 30,
    from: 9,
    to: 6,
    hebrew: "ריש",
    meaning: "Head",
    tarot: "The Sun",
    astrology: ["Sol"],
    color: "Golden Yellow",
    stone: "Golden Topaz",
    plant: "Laurel",
    image: "Joyful illumination",
    virtue: "Joy",
    advice: "Celebrate successes",
    warning: "Arrogance blinds"
  },
  {
    id: 31,
    from: 3,
    to: 6,
    hebrew: "תיו",
    meaning: "Mark",
    tarot: "Judgment",
    astrology: ["Pluto"],
    color: "Scarlet Red",
    stone: "Fire Opal",
    plant: "Ash",
    image: "Final reckoning",
    virtue: "Renewal",
    advice: "Face judgment fairly",
    warning: "Denial prolongs suffering"
  },
  {
    id: 32,
    from: 9,
    to: 10,
    hebrew: "תיו",
    meaning: "Cross",
    tarot: "The World",
    astrology: ["Saturn"],
    color: "Indigo",
    stone: "Chrysoberyl",
    plant: "Ivory",
    image: "Cosmic completion",
    virtue: "Integration",
    advice: "Unity in diversity",
    warning: "Separation divides"
  }
];
